@startuml NaNAirlines

package UI_layer #4FDEDD {
  class MainUI{
    main_menu()
    menu_handler()
  }

  class EmployeeUI{
    show()
    list()
    create()
    edit()
  }
  class VoyagesUI{
    show()
    list()
    create()
    edit()
  }
  class DestinationsUI{
    show()
    list()
    create()
    edit()
  }
  class AirplanesUI{
    show()
    list()
    create()
    edit()
  }
  MainUI -- EmployeeUI
  MainUI -- VoyagesUI
  MainUI -- DestinationsUI
  MainUI -- AirplanesUI
}

package Logic_layer #666C69 {

  class EmployeeLL{
    validate_input()
    
  }
  class VoyagesLL{
    validate_input()
    
  }
  class DestinationsLL{
    validate_input()
    
  }
  class AirplanesLL{
    validate_input()
    
  }

}

package Data_layer{

  class EmployeeDL{
    save_data()
    read_data()
    create_instance()
  }
  class VoyagesDL{
    save_data()
    read_data()
    create_instance()
    
  }
  class DestinationsDL{
    save_data()
    read_data()
    create_instance()
    
  }
  class AirplanesDL{
    save_data()
    read_data()
    create_instance()
    
  }
  
}



package Models{


class Employee {
  name
  id_number
  address
  home_number
  mobile_number
  email
  title
  availability

  get_name()
  set_name()
  get_id_number()
  set_id_number()
  get_home_number()
  set_home_number()
  get_mobile_number()
  set_mobile_number()
  get_email()
  set_email()
  get_title()
  set_title()
  get_availability()
  set_availability()
}

class Flight_attendant{
}

class Pilot{
  flight_licenses

  get_flight_licenses()
  set_flight_licenses()
}

class Destination{
  name
  airport
  flight_time
  distance
  contact_name
  contact_number

  get_name()
  set_name()
  get_airport()
  set_airport()
  get_flight_time()
  set_flight_time()
  get_distance()
  set_distance()
  get_contact_name()
  set_contact_name()
  get_contact_number()
  set_contact_number()
}

class Voyage{
  pilot
  co_pilot
  purser
  cabin_crew_list

  get_pilot()
  set_pilot()
  get_co_pilot()
  set_co_pilot()
  get_purser()
  set_purser()
  get_cabin_crew_list()
  set_cabin_crew_list()

}

class Flight{
  departure_airport
  arrival_airport
  departure_date
  departure_time
  arrival_date
  arrival_time
  flight_num
  flight_id

  get_destination()
  set_destination()
  get_departure_date()
  set_departure_date()
  get_departure_time()
  set_departure_time()
  get_flight_num()
  set_flight_num()
  get_flight_id()
  set_flight_id()
}

class Airplane{
  model
  max_seats

  get_model()
  set_model()
  get_max_seats()
  set_max_seats()
}

Employee -up-|> Flight_attendant
Employee -up-|> Pilot
Destination *-- Voyage
Airplane *-- Flight
Airplane *-- Voyage
Flight *-- Voyage

}



UI_layer -down- Logic_layer
Logic_layer -down- Data_layer

UI_layer -- Models
Logic_layer -- Models
Data_layer -- Models


@enduml