@startuml NaNAirlines

class chuckNaN{
  UIMain

}

package UI_layer #fcb603 {
 
  chuckNaN -down- UIMain
  class UIMain{
    UIEmployees
    UIVoyages
    UIDestinations
    UIAirplanes
    print_main_menu()
    menu_handler()
  }

  class UIEmployees{
    LLMain
    print_sub_menu()
    print_seach_menu()
    print_formatted_list()
    print_create_employee()
    print_selected_employee()
    print_edit_menu()
  }
  class UIVoyages{
    LLMain
    print_sub_menu()
    print_seach_menu()
    print_formatted_list()
    print_create_voyage()
    print_selected_voyage()
    print_edit_menu()
  }
  class UIDestinations{
    LLMain
    print_sub_menu()
    print_seach_menu()
    print_formatted_list()
    print_create_destination()
    print_selected_destination()
    print_edit_menu()
  }
  class UIAirplanes{
    LLMain
    print_sub_menu()
    print_seach_menu()
    print_formatted_list()
    print_create_airplane()
    print_selected_airplane()
    print_edit_menu()
  }
  UIMain -- UIEmployees
  UIMain -- UIVoyages
  UIMain -- UIDestinations
  UIMain -- UIAirplanes
}

package Logic_layer #70e697 {

  class LLMain{
    LLEmployees
    LLVoyages
    LLDestinations
    LLAirplanes


  }

  class LLEmployees{
    DLMain
    validate_input()
    
  }
  class LLVoyages{
    DLMain
    validate_input()
    
  }
  class LLDestinations{
    DLMain
    validate_input()
    
  }
  class LLAirplanes{
    DLMain
    validate_input()
    
  }

  LLMain -- LLEmployees
  LLMain -- LLVoyages
  LLMain -- LLDestinations
  LLMain -- LLAirplanes

}

package Data_layer #99c0ff{

  class DLMain{
    DLEmployees
    DLVoyages
    DLDestinations
    DLAirplanes

  }

  class DLEmployees{
    save_data()
    read_data()
    create_instance()
  }
  class DLVoyages{
    save_data()
    read_data()
    create_instance()
    
  }
  class DLDestinations{
    save_data()
    read_data()
    create_instance()
    
  }
  class DLAirplanes{
    save_data()
    read_data()
    create_instance()
    
  }

  DLMain -- DLEmployees
  DLMain -- DLVoyages
  DLMain -- DLDestinations
  DLMain -- DLAirplanes
  
}

UIEmployees -down- LLMain
UIVoyages -down- LLMain
UIAirplanes -down- LLMain
UIDestinations -down- LLMain

LLEmployees -down- DLMain
LLVoyages -down- DLMain
LLDestinations -down- DLMain
LLAirplanes -down- DLMain






package Models #f58ef0{


class Employee {
  name
  id_number
  address
  home_number
  mobile_number
  email
  title
  availability

  get_name()
  set_name()
  get_id_number()
  set_id_number()
  get_home_number()
  set_home_number()
  get_mobile_number()
  set_mobile_number()
  get_email()
  set_email()
  get_title()
  set_title()
  get_availability()
  set_availability()
}

class Flight_attendant{
}

class Pilot{
  flight_licenses

  get_flight_licenses()
  set_flight_licenses()
}

class Destination{
  name
  airport
  flight_time
  distance
  contact_name
  contact_number

  get_name()
  set_name()
  get_airport()
  set_airport()
  get_flight_time()
  set_flight_time()
  get_distance()
  set_distance()
  get_contact_name()
  set_contact_name()
  get_contact_number()
  set_contact_number()
}

class Voyage{
  pilot
  co_pilot
  purser
  cabin_crew_print_formatted_list

  get_pilot()
  set_pilot()
  get_co_pilot()
  set_co_pilot()
  get_purser()
  set_purser()
  get_cabin_crew_print_formatted_list()
  set_cabin_crew_print_formatted_list()

}

class Flight{
  departure_airport
  arrival_airport
  departure_date
  departure_time
  arrival_date
  arrival_time
  flight_num
  flight_id

  get_destination()
  set_destination()
  get_departure_date()
  set_departure_date()
  get_departure_time()
  set_departure_time()
  get_flight_num()
  set_flight_num()
  get_flight_id()
  set_flight_id()
}

class Airplane{
  model
  max_seats

  get_model()
  set_model()
  get_max_seats()
  set_max_seats()
}

Employee -up-|> Flight_attendant
Employee -up-|> Pilot
Destination *-- Voyage
Airplane *-- Flight
Airplane *-- Voyage
Flight *-- Voyage

}


UI_layer -- Models
Logic_layer -- Models
Data_layer -- Models


@enduml