@startuml

[*] --> In_use
[*] --> Not_in_use
In_use -> On_the_ground
On_the_ground : Reykjavik
On_the_ground : Kulusuk
On_the_ground : Torshavn
On_the_ground : Nuuk
On_the_ground : Tingwall
On_the_ground : Longyearbyen 
In_use --> In_the_air
In_the_air -> On_the_ground
On_the_ground -> In_the_air

Not_in_use --> [*]
On_the_ground --> [*]

@enduml