@startuml add_Crew
hide empty description
[*] --> UI_voyage_menu
UI_voyage_menu --> LL_voyage_handler:get list
LL_voyage_handler --> DL_voyage_handler:get list
DL_voyage_handler --> DB :get data \nfor list
DB --> DL_voyage_handler :send data \nfor list
DL_voyage_handler --> LL_voyage_handler: send data \nfor list
LL_voyage_handler -right-> voyage_list:send list


voyage_list --> UI_voyage_search
UI_voyage_search --> UI_empty_voyages


UI_empty_voyages--> UI_voyage: found voyage
crew_list --> LL_voyage_handler:get list of crews
LL_voyage_handler --> crew_list:send list \nof available crews
UI_voyage --> crew_list
crew_list --> add_crew_to_voyage:select crew
add_crew_to_voyage --> LL_voyage_handler1
LL_voyage_handler1 --> DL_voyage_handler1
DL_voyage_handler1 --> DB1
DB1 --> [*]
@enduml