@startuml create employee
hide empty description


[*] --> create_employee
create_employee --> UI_input_name
UI_input_name --> UI_input_name:invalid input
UI_input_name --> UI_input_ssn
UI_input_ssn --> UI_input_ssn::invalid input
UI_input_ssn --> UI_input_home_number
UI_input_home_number --> UI_input_home_number:invalid input
UI_input_home_number --> UI_input_mobile_number
UI_input_mobile_number --> UI_input_mobile_number:invalid input
UI_input_mobile_number --> UI_input_email
UI_input_email --> UI_input_email:invalid input
UI_input_email --> UI_input_title
UI_input_title --> UI_input_title:invalid input
UI_input_title --> [*]
UI_input_title --> UI_input_licenses: if title == pilot or if title == co-pilot
UI_input_licenses --> UI_input_licenses: invalid input
UI_input_licenses --> [*]
@enduml