@startuml UI_states
hide empty description
MainMenu: 1. Employees \n2. Voyages \n3. Destinations \n4. Airplanes

state Employee_state #fcb603{

    MainMenu #fa939a -Left-> Employees: 1
    Employees: 1. CreateEmployee \n2. AllEmployees \n3. EmployeeSearch
    Employees -up-> CreateEmployee: Krafa 1
    CreateEmployee: 1. Prompt for relevant data \n2. ValidateDataUI \n3. ValidateDataLL\n4. StoreInDB
    Employees -up-> AllEmployees: Krafa 2
    AllEmployees -up-> ShowEmployees
    Employees -down-> EmployeeSearch
    EmployeeSearch --> ByTitle: Krafa 3
    ByTitle --> ShowEmployees
    ShowEmployees: 1. Select Employee \n2. ShowWorking \n3. ShowFree
    EmployeeSearch --> BySSN: Krafa 4
    BySSN --> ShowEmployee
    ShowEmployee: 1. EditEmployee \n2. WorkSchedule\n3. AddLicense
    ShowEmployee --> EditEmployee: Krafa 5
    EditEmployee: 1. Home Number \n2. Mobile Number \n3. Email \n4. Title
    ShowEmployee --> WorkSchedule: Krafa 15
    WorkSchedule --> ShowWorkSchedule: Input:Period
    EmployeeSearch --> ByDate
    ByDate --> ShowEmployees
    EmployeeSearch --> ByAirplane
    ByAirplane --> SortByAirplane: Krafa 20
    ByAirplane --> FilterByAirplane: Krafa 19
    SortByAirplane --> ShowEmployees
    FilterByAirplane --> ShowEmployees: Input: Airplane Type
    EmployeeSearch: 1. BySSN\n2. ByTitle\n3. ByDate\n4. ByAirplane


    ShowEmployees --> ShowFree: Krafa 13
    ShowEmployees --> ShowWorking: Krafa 14
    ShowEmployees --> ShowEmployee: Select Employee
    ShowEmployee --> AddLicense: Krafa 18
    AddLicense: If Employee == Pilot or Co-Pilot

}


state Voyages_state #f58ef0{
    MainMenu -Down-> Voyages: 2
    Voyages: 1. Create Voyage \n2. AllVoyages \n3. VoyageSearch
    Voyages --> CreateVoyage: Krafa 8
    Voyages --> AllVoyages: Krafa 9
    AllVoyages --> ShowVoyages
    Voyages --> VoyageSearch
    VoyageSearch: 1. ByDestination \n2. ByPeriod \n3. EmptyVoyages \n4. StaffedVoyages
    VoyageSearch --> ByDestination
    VoyageSearch --> EmptyVoyages
    VoyageSearch --> ByPeriod
    ByDestination --> ShowVoyages
    StaffedVoyages --> ShowVoyages: Krafa 11

    EmptyVoyages --> ShowVoyages
    ByPeriod --> ShowVoyages: Krafa 12
    ShowVoyages --> ShowVoyage: Select
    ShowVoyage: 1. AddCrew\n 2. Duplicate\n 3. Repeat
    ShowVoyage --> AddCrew: Krafa 10
    VoyageSearch --> StaffedVoyages
    ShowVoyage --> DuplicateVoyage: Krafa 16
    DuplicateVoyage: input: Date \nCheck if time and airplane are available
    ShowVoyage --> RepeatVoyage: Krafa 16
    RepeatVoyage: 1. input: Period \n2. input: Interval


}

state Destination_state #70e697{
    MainMenu -Right-> Destinations: 3
    Destinations:1. Create Destination \n2. AllDestinations \n3. DestinationSearch
    Destinations -up-> CreateDestination: Krafa 6
    Destinations -down-> AllDestinations: Krafa 7
    ShowDestinations --> ShowDestination: Select
    AllDestinations --> ShowDestinations
    Destinations -right-> DestinationSearch
    DestinationSearch: input("Name of Destination")
    DestinationSearch --> ShowDestination: User input for name
    ShowDestination: 1. ChangeContact \n2. ChangeEmergencyNumber
    ShowDestination --> ChangeContact: Krafa 21
    ShowDestination --> ChangeEmergencyNumber: Krafa 22

}

state Airplanes_state #99c0ff{
    MainMenu -up-> Airplanes:4 
    Airplanes: 1. CreateAirplane \n2. AllPlanes
    Airplanes -left-> CreateAirplane: Krafa 17
    Airplanes -right-> AllPlanes: Krafa 23
    AllPlanes -up-> ShowPlanes
    
    

}

@enduml